---
- hosts: all
  become: false
  remote_user: danclark

  tasks:

    - name: Create a wordpress namespace
      k8s:
        host: "{{ cluster_api }}"
        name: wordpress
        api_version: v1
        kind: Namespace
        state: present
        validate_certs: "{{ validate_certs }}"
        wait: true
        api_key: 'sPtWfIK3oBWiPmZdOqVbt0IN6CPefT5aEOfJlKZQbkY'
#        kubeconfig: "{{ kubeconfig }}"

#    - name: Create Wordpress Database PVC
#      k8s:
#        state: present
#        definition: "{{ lookup('file', 'wordpress-db-pvc.yaml') }}"
#        namespace: wordpress
#        validate_certs: "{{ validate_certs }}"
#        wait: true
#        kubeconfig: "{{ kubeconfig }}"

#    - name: Create Wordpress PVC
#      k8s:
#        state: present
#        definition: "{{ lookup('file', 'wordpress-data-pvc.yaml') }}"
#        namespace: wordpress
#        validate_certs: "{{ validate_certs }}"
#        wait: true
#        kubeconfig: "{{ kubeconfig }}"

    - name: Create Wordpress Database
      k8s:
        state: present
        definition: "{{ lookup('file', 'mysql.yaml') }}"
        namespace: wordpress
        validate_certs: "{{ validate_certs }}"
        wait: true
        api_key: 'sPtWfIK3oBWiPmZdOqVbt0IN6CPefT5aEOfJlKZQbkY'
#        kubeconfig: "{{ kubeconfig }}"

    - name: Create Wordpress
      k8s:
        state: present
        definition: "{{ lookup('file', 'wordpress.yaml') }}"
        namespace: wordpress
        validate_certs: "{{ validate_certs }}"
        wait: true
        api_key: 'sPtWfIK3oBWiPmZdOqVbt0IN6CPefT5aEOfJlKZQbkY'
#        kubeconfig: "{{ kubeconfig }}"
