apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-data-pv
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /opt/nfs/pv-0002
    server: 10.0.106.71
  persistentVolumeReclaimPolicy: Retain
